//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImagingOrder
    {
        public int ID { get; set; }
        public Nullable<int> OPDId { get; set; }
        public Nullable<int> ImagingId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public byte[] ImageResult { get; set; }
        public string ResultDescription { get; set; }
        public string OrderStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> VisitId { get; set; }
    
        public virtual tbl_OrderStatus tbl_OrderStatus { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
    }
}
