//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LaboratoryOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_LaboratoryOrder()
        {
            this.tbl_LabOrderLabparam = new HashSet<tbl_LabOrderLabparam>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OPDId { get; set; }
        public Nullable<int> LaboratoryID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string OrderStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> VisitId { get; set; }
        public Nullable<bool> Payment { get; set; }
    
        public virtual tbl_Visit tbl_Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LabOrderLabparam> tbl_LabOrderLabparam { get; set; }
    }
}
