//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patient_Vital
    {
        public int ID { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> VitalParamId { get; set; }
        public string ResultValue { get; set; }
        public Nullable<int> VisitId { get; set; }
    }
}
