//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Visit()
        {
            this.tbl_LaboratoryOrder = new HashSet<tbl_LaboratoryOrder>();
            this.tbl_PatientHistory = new HashSet<tbl_PatientHistory>();
            this.tbl_Prescription = new HashSet<tbl_Prescription>();
            this.tbl_Vital = new HashSet<tbl_Vital>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string VisitType { get; set; }
        public Nullable<int> VisitStatus { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> OPDId { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string Diagnosis { get; set; }
        public string DoctorComment { get; set; }
        public Nullable<int> Prescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LaboratoryOrder> tbl_LaboratoryOrder { get; set; }
        public virtual tbl_Patient tbl_Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PatientHistory> tbl_PatientHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Prescription> tbl_Prescription { get; set; }
        public virtual tbl_Staff tbl_Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Vital> tbl_Vital { get; set; }
    }
}
