//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LabOrderLabparam
    {
        public int ID { get; set; }
        public Nullable<int> LabOrderId { get; set; }
        public Nullable<int> LabOrderParamId { get; set; }
        public string Result { get; set; }
    
        public virtual tbl_LaboratoryOrder tbl_LaboratoryOrder { get; set; }
        public virtual tbl_LabOrderparams tbl_LabOrderparams { get; set; }
    }
}
