//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NurseOrder
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> OPDId { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> VisitId { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    }
}
