//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewTimeline
    {
        public int VId { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string VisitType { get; set; }
        public string Diagnosis { get; set; }
        public string DoctorComment { get; set; }
        public string OpdName { get; set; }
        public int ID { get; set; }
        public string BloodPressure { get; set; }
        public string PulseRate { get; set; }
        public string OxygenLevel { get; set; }
        public string BedyWeight { get; set; }
        public string Temprature { get; set; }
        public string Height { get; set; }
        public string Allergic { get; set; }
        public string Others { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> VisitId { get; set; }
    }
}
